<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INGUEUCLP000666" ignored="0" name="Dependency Test" tests="4" failures="2" timestamp="24 Jul 2019 19:30:22 GMT" time="0.021" errors="0">
  <testcase name="A" time="0.001" classname="testngLearning.DependencyTest">
    <failure type="java.lang.AssertionError" message="Failed to test dependency">
      <![CDATA[java.lang.AssertionError: Failed to test dependency
at testngLearning.DependencyTest.A(DependencyTest.java:15)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase name="C" time="0.001" classname="testngLearning.DependencyTest">
    <failure type="java.lang.AssertionError" message="Failed due to some reason">
      <![CDATA[java.lang.AssertionError: Failed due to some reason
at testngLearning.DependencyTest.C(DependencyTest.java:28)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- C -->
  <testcase name="B" time="0.0" classname="testngLearning.DependencyTest">
    <skipped/>
  </testcase> <!-- B -->
  <testcase name="D" time="0.001" classname="testngLearning.DependencyTest"/>
</testsuite> <!-- Dependency Test -->
